# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '\u677f\u5757', 'verbose_name_plural': '\u677f\u5757'},
        ),
        migrations.AlterField(
            model_name='block',
            name='block_name',
            field=models.CharField(max_length=20, verbose_name='\u677f\u5757\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='block',
            name='discribe',
            field=models.CharField(max_length=30, verbose_name='\u677f\u5757\u63cf\u8ff0'),
        ),
    ]
